"""add tempvoice and tickets tables

Revision ID: 3b22e11c3530
Revises: b51c9cd83f6d
Create Date: 2026-09-06 14:43:14.689122

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b22e11c3530"
down_revision: Union[str, Sequence[str], None] = "b51c9cd83f6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "temp_voice_channels",
        sa.Column("channel_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("panel_message_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("channel_id"),
    )
    with op.batch_alter_table("temp_voice_channels", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_temp_voice_channels_guild_id"), ["guild_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_temp_voice_channels_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "ticket_panel_setup",
        sa.Column("channel_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("channel_id"),
    )
    with op.batch_alter_table("ticket_panel_setup", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ticket_panel_setup_guild_id"), ["guild_id"], unique=False
        )

    op.create_table(
        "tickets",
        sa.Column("channel_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("panel_message_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_activity_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("warned_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("channel_id"),
    )
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tickets_guild_id"), ["guild_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tickets_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tickets_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tickets_status"))
        batch_op.drop_index(batch_op.f("ix_tickets_owner_id"))
        batch_op.drop_index(batch_op.f("ix_tickets_guild_id"))

    op.drop_table("tickets")
    with op.batch_alter_table("ticket_panel_setup", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ticket_panel_setup_guild_id"))

    op.drop_table("ticket_panel_setup")
    with op.batch_alter_table("temp_voice_channels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_temp_voice_channels_owner_id"))
        batch_op.drop_index(batch_op.f("ix_temp_voice_channels_guild_id"))

    op.drop_table("temp_voice_channels")
    # ### end Alembic commands ###
