"""add create voice model

Revision ID: 6f3f5b942ade
Revises: 3b22e11c3530
Create Date: 2026-09-08 01:38:49.662247

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f3f5b942ade"
down_revision: Union[str, Sequence[str], None] = "3b22e11c3530"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "create_voice_channels",
        sa.Column("channel_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("channel_id"),
    )
    with op.batch_alter_table("create_voice_channels", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_create_voice_channels_guild_id"), ["guild_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("create_voice_channels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_create_voice_channels_guild_id"))

    op.drop_table("create_voice_channels")
    # ### end Alembic commands ###
