"""Initial migration

Revision ID: b51c9cd83f6d
Revises: 
Create Date: 2026-09-05 17:31:10.486237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51c9cd83f6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marked_channels',
    sa.Column('channel_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('marked_by', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('ban_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('channel_id')
    )
    with op.batch_alter_table('marked_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marked_channels_guild_id'), ['guild_id'], unique=False)

    op.create_table('users_economy',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('connhen', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('last_daily', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_economy')
    with op.batch_alter_table('marked_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marked_channels_guild_id'))

    op.drop_table('marked_channels')
    # ### end Alembic commands ###
